name: urs_beauty
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
dependencies:
  app_links: ^6.4.0
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  iconsax: ^0.0.8
  go_router: ^16.0.0
  dartz: ^0.10.1
  lottie: ^3.3.1
  flutter_onboarding: ^1.0.6
  flutter_animate: ^4.5.2
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/welcome.png