create table if not exists public.booking_services (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings (id) on delete cascade,
  service_name text not null,
  service_id integer not null references public.service (id),
  stylist_service_id integer not null references public.stylists_services (id),
  quantity integer not null check (quantity > 0),
  price_at_booking numeric(10, 2) not null check (price_at_booking >= 0),
  duration_at_booking integer not null check (duration_at_booking >= 0),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_booking_services_booking_id
  on public.booking_services (booking_id);

create index if not exists idx_booking_services_service_id
  on public.booking_services (service_id);

create index if not exists idx_booking_services_stylist_service_id
  on public.booking_services (stylist_service_id);

alter table public.booking_services enable row level security;

drop policy if exists "Customers can view their booking services"
  on public.booking_services;

create policy "Customers can view their booking services"
  on public.booking_services
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.bookings b
      where b.id = booking_services.booking_id
        and b.customer = auth.uid()
    )
  );

drop policy if exists "Stylists can view assigned booking services"
  on public.booking_services;

create policy "Stylists can view assigned booking services"
  on public.booking_services
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.bookings b
      where b.id = booking_services.booking_id
        and b.stylist = auth.uid()
    )
  );

create or replace function public.create_booking_with_services(
  p_customer_id uuid,
  p_stylist_id uuid,
  p_scheduled_at timestamptz,
  p_address text,
  p_notes text default null,
  p_items jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_quantity integer;
  v_total_amount numeric(10, 2) := 0;
  v_total_duration integer := 0;
  v_booking public.bookings%rowtype;
  v_service_snapshot record;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if auth.uid() <> p_customer_id then
    raise exception 'Authenticated user does not match booking customer';
  end if;

  if p_scheduled_at <= timezone('utc', now()) then
    raise exception 'Scheduled time must be in the future';
  end if;

  if p_address is null or btrim(p_address) = '' then
    raise exception 'Booking address is required';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'At least one service item is required';
  end if;

  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    v_quantity := coalesce((v_item ->> 'quantity')::integer, 0);

    if v_quantity <= 0 then
      raise exception 'Each booking item must have a quantity greater than zero';
    end if;

    select
      ss.id,
      ss.stylists_id,
      ss.service_id,
      ss.price,
      s.name as service_name,
      coalesce(s.duration_minutes, 0) as duration_minutes
    into v_service_snapshot
    from public.stylists_services ss
    join public.service s
      on s.id = ss.service_id
    where ss.id = (v_item ->> 'stylist_service_id')::integer
      and ss.service_id = (v_item ->> 'service_id')::integer
      and ss.stylists_id = p_stylist_id
      and coalesce(ss.is_available, true) = true;

    if not found then
      raise exception 'Invalid service selection for the selected stylist';
    end if;

    v_total_amount := v_total_amount + (v_service_snapshot.price * v_quantity);
    v_total_duration := v_total_duration
      + (v_service_snapshot.duration_minutes * v_quantity);
  end loop;

  insert into public.bookings (
    customer,
    stylist,
    status,
    notes,
    address,
    total_amount,
    scheduled_at,
    end_at,
    created_at,
    updated_at
  )
  values (
    p_customer_id,
    p_stylist_id,
    'pending',
    nullif(btrim(coalesce(p_notes, '')), ''),
    btrim(p_address),
    v_total_amount,
    p_scheduled_at,
    p_scheduled_at + make_interval(mins => v_total_duration),
    timezone('utc', now()),
    timezone('utc', now())
  )
  returning *
  into v_booking;

  for v_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item ->> 'quantity')::integer;

    select
      ss.id,
      ss.service_id,
      ss.price,
      s.name as service_name,
      coalesce(s.duration_minutes, 0) as duration_minutes
    into v_service_snapshot
    from public.stylists_services ss
    join public.service s
      on s.id = ss.service_id
    where ss.id = (v_item ->> 'stylist_service_id')::integer
      and ss.service_id = (v_item ->> 'service_id')::integer
      and ss.stylists_id = p_stylist_id
      and coalesce(ss.is_available, true) = true;

    insert into public.booking_services (
      booking_id,
      service_name,
      service_id,
      stylist_service_id,
      quantity,
      price_at_booking,
      duration_at_booking
    )
    values (
      v_booking.id,
      v_service_snapshot.service_name,
      v_service_snapshot.service_id,
      v_service_snapshot.id,
      v_quantity,
      v_service_snapshot.price,
      v_service_snapshot.duration_minutes
    );
  end loop;

  return to_jsonb(v_booking);
end;
$$;

grant execute on function public.create_booking_with_services(
  uuid,
  uuid,
  timestamptz,
  text,
  text,
  jsonb
) to authenticated;


